-- Secuencia para Manufacturer
CREATE SEQUENCE SEQ_MANUFACTURER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para ElectronicComponent
CREATE SEQUENCE SEQ_ELECTRONICCOMPONENT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE MANUFACTURER (
    ID                NUMBER          NOT NULL,
    NAME              VARCHAR2(50)    NOT NULL,
    COUNTRY           VARCHAR2(50)    NOT NULL,
    CREATED_AT        DATE            NOT NULL,
    AVERAGE_LEAD_TIME NUMBER          NOT NULL,
    CONSTRAINT PK_ID        PRIMARY KEY (ID),
    CONSTRAINT CHK_LEADTIME CHECK (AVERAGE_LEAD_TIME > 0 AND AVERAGE_LEAD_TIME <= 365)
);

CREATE TABLE ELECTRONICCOMPONENT (
    ID              NUMBER          NOT NULL,
    PIN_COUNT       NUMBER          NOT NULL,
    PACKAGE_TYPE    VARCHAR2(20),
    VOLTAGE         NUMBER          NOT NULL,
    CREATED_AT      DATE            NOT NULL,
    TOLERANCE       NUMBER          NOT NULL,
    NOMINAL_VALUE   NUMBER          NOT NULL,
    NOMINAL_UNIT    VARCHAR2(20),
    ID_MANUFACTURER NUMBER          NOT NULL,
    CONSTRAINT PK_ECID          PRIMARY KEY (ID),
    CONSTRAINT FK_IDMANUFACTER  FOREIGN KEY (ID_MANUFACTURER) REFERENCES MANUFACTURER(ID),
    CONSTRAINT CHK_PACKAGETYPE  CHECK (PACKAGE_TYPE IN ('SMD','DIP','SIP','QFP','BGA','SOT','TO','AXIAL')),
    CONSTRAINT CHK_VOLTAGE      CHECK (VOLTAGE > 0 AND VOLTAGE <= 1000),
    CONSTRAINT CHK_PINCOUNT     CHECK (PIN_COUNT > 0 AND PIN_COUNT <= 1000),
    CONSTRAINT CHK_TOLERANCE    CHECK (TOLERANCE >= 0 AND TOLERANCE <= 1),
    CONSTRAINT CHK_NOMINALVALUE CHECK (NOMINAL_VALUE > 0)
);

SELECT * FROM MANUFACTURER;
SELECT * FROM ELECTRONICCOMPONENT;

DROP TABLE ELECTRONICCOMPONENT; 
DROP TABLE MANUFACTURER;