-- ============================================================
-- SQL CORREGIDO - Tercer Prototipo 2026A
-- Ejecutar manualmente en Oracle antes de iniciar la app
-- ============================================================

CREATE TABLE MANUFACTURER (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME            VARCHAR2(50)    NOT NULL,
    COUNTRY         VARCHAR2(50)    NOT NULL,
    CREATEDAT       TIMESTAMP       NOT NULL,
    AVERAGELEADTIME NUMBER(10,2)    NOT NULL,
    CONSTRAINT PK_MANUFACTURER PRIMARY KEY (ID),
    CONSTRAINT CHK_LEADTIME CHECK (AVERAGELEADTIME > 0 AND AVERAGELEADTIME <= 365)
);

CREATE TABLE ELECTRONICCOMPONENT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY,
    PINCOUNT        NUMBER          NOT NULL,
    PACKAGETYPE     VARCHAR2(20),
    VOLTAGE         NUMBER(10,2)    NOT NULL,
    CREATEDAT       TIMESTAMP       NOT NULL,
    TOLERANCE       NUMBER(5,4)     NOT NULL,
    NOMINALVALUE    NUMBER(15,4)    NOT NULL,
    NOMINALUNIT     VARCHAR2(10),
    IDMANUFACTURER  NUMBER          NOT NULL,
    CONSTRAINT PK_ELECTRONICCOMPONENT  PRIMARY KEY (ID),
    CONSTRAINT FK_IDMANUFACTURER       FOREIGN KEY (IDMANUFACTURER) REFERENCES MANUFACTURER(ID),
    CONSTRAINT CHK_PACKAGETYPE         CHECK (PACKAGETYPE IN ('SMD','DIP','SIP','QFP','BGA','SOT','TO','AXIAL')),
    CONSTRAINT CHK_VOLTAGE             CHECK (VOLTAGE > 0 AND VOLTAGE <= 1000),
    CONSTRAINT CHK_PINCOUNT            CHECK (PINCOUNT > 0 AND PINCOUNT <= 1000),
    CONSTRAINT CHK_TOLERANCE           CHECK (TOLERANCE >= 0 AND TOLERANCE <= 1),
    CONSTRAINT CHK_NOMINALVALUE        CHECK (NOMINALVALUE > 0)
);
